---
title: "Session 2: Homework 1"
author: "MFA2021 Study Group 13A"
date: "2020-09-27"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<div id="where-do-people-drink-the-most-beer-wine-and-spirits" class="section level1">
<h1>Where Do People Drink The Most Beer, Wine And Spirits?</h1>
<pre class="r"><code>library(fivethirtyeight)
data(drinks)


# or download directly
# alcohol_direct &lt;- read_csv(&quot;https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv&quot;)</code></pre>
<p>What are the variable types? Any missing values we should worry about?</p>
<pre class="r"><code># YOUR CODE GOES HERE
glimpse(drinks)</code></pre>
<pre><code>## Rows: 193
## Columns: 5
## $ country                      &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;An…
## $ beer_servings                &lt;int&gt; 0, 89, 25, 245, 217, 102, 193, 21, 261, …
## $ spirit_servings              &lt;int&gt; 0, 132, 0, 138, 57, 128, 25, 179, 72, 75…
## $ wine_servings                &lt;int&gt; 0, 54, 14, 312, 45, 45, 221, 11, 212, 19…
## $ total_litres_of_pure_alcohol &lt;dbl&gt; 0.0, 4.9, 0.7, 12.4, 5.9, 4.9, 8.3, 3.8,…</code></pre>
<pre class="r"><code>skim(drinks)</code></pre>
<table>
<caption>(#tab:glimpse_skim_data)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">drinks</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">193</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">country</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">28</td>
<td align="right">0</td>
<td align="right">193</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">beer_servings</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">106.16</td>
<td align="right">101.14</td>
<td align="right">0</td>
<td align="right">20.0</td>
<td align="right">76.0</td>
<td align="right">188.0</td>
<td align="right">376.0</td>
<td align="left">▇▃▂▂▁</td>
</tr>
<tr class="even">
<td align="left">spirit_servings</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">80.99</td>
<td align="right">88.28</td>
<td align="right">0</td>
<td align="right">4.0</td>
<td align="right">56.0</td>
<td align="right">128.0</td>
<td align="right">438.0</td>
<td align="left">▇▃▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">wine_servings</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">49.45</td>
<td align="right">79.70</td>
<td align="right">0</td>
<td align="right">1.0</td>
<td align="right">8.0</td>
<td align="right">59.0</td>
<td align="right">370.0</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">total_litres_of_pure_alcohol</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4.72</td>
<td align="right">3.77</td>
<td align="right">0</td>
<td align="right">1.3</td>
<td align="right">4.2</td>
<td align="right">7.2</td>
<td align="right">14.4</td>
<td align="left">▇▃▅▃▁</td>
</tr>
</tbody>
</table>
<p>Make a plot that shows the top 25 beer consuming countries</p>
<pre class="r"><code># YOUR CODE GOES HERE
top_25_beer &lt;- drinks %&gt;% 
  arrange(desc(beer_servings)) %&gt;%
  slice(1:25)

ggplot(top_25_beer, aes(x = reorder(country, beer_servings), y = beer_servings))+ 
  geom_col() + 
  coord_flip() +
  theme(axis.text.x = element_text(size = 14, margin=margin(15,0,0,0)),
        axis.text.y = element_text(size = 14, margin = margin(0,15,0,0)),
        plot.title = element_text(size = 18, face = &quot;bold&quot;, margin = margin(0,0,30,0)), 
        axis.title.x = element_text(size=15, face=&quot;bold&quot;, margin=margin(20,0,0,0)),
        axis.title.y = element_text(size=15, face=&quot;bold&quot;))+
  labs(x=&quot;Country&quot;, 
       y=&quot;Beer Servings&quot;, 
       title=&quot;Top 25 beer serving countries&quot;)</code></pre>
<p><img src="/project1/project1_files/figure-html/beer_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Make a plot that shows the top 25 wine consuming countries</p>
<pre class="r"><code># YOUR CODE GOES HERE
top_25_wine &lt;- drinks %&gt;% 
  arrange(desc(wine_servings)) %&gt;%
  slice(1:25)

ggplot(top_25_wine, aes(x=reorder(country, wine_servings), y=wine_servings)) + 
  geom_col() + 
  coord_flip() +
  theme(axis.text.x = element_text(size = 14, margin=margin(15,0,0,0)),
        axis.text.y = element_text(size = 14, margin = margin(0,15,0,0)),
        plot.title = element_text(size = 18, face = &quot;bold&quot;, margin = margin(0,0,30,0)), 
        axis.title.x = element_text(size=15, face=&quot;bold&quot;, margin=margin(20,0,0,0)),
        axis.title.y = element_text(size=15, face=&quot;bold&quot;))+
  labs(x=&quot;Country&quot;, 
       y=&quot;Wine Servings&quot;, 
       title=&quot;Top 25 wine serving countries&quot;)</code></pre>
<p><img src="/project1/project1_files/figure-html/wine_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Finally, make a plot that shows the top 25 spirit consuming countries</p>
<pre class="r"><code># YOUR CODE GOES HERE
top_25_spirit &lt;- drinks %&gt;% 
  arrange(desc(spirit_servings)) %&gt;%
  slice(1:25)

ggplot(top_25_spirit, aes(x=reorder(country, spirit_servings), y=spirit_servings))+ 
  geom_col() + 
  coord_flip() +
  theme(axis.text.x = element_text(size = 14, margin=margin(15,0,0,0)),
        axis.text.y = element_text(size = 14, margin = margin(0,15,0,0)),
        plot.title = element_text(size = 18, face = &quot;bold&quot;, margin = margin(0,0,30,0)), 
        axis.title.x = element_text(size=15, face=&quot;bold&quot;, margin=margin(20,0,0,0)),
        axis.title.y = element_text(size=15, face=&quot;bold&quot;))+
  labs(x=&quot;Country&quot;, 
       y=&quot;Spirit Servings&quot;, 
       title=&quot;Top 25 spirit serving countries&quot;)</code></pre>
<p><img src="/project1/project1_files/figure-html/spirit_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>What can you infer from these plots? Don’t just explain what’s in the graph, but speculate or tell a short story (1-2 paragraphs max).</p>
<blockquote>
<p>TYPE YOUR ANSWER AFTER (AND OUTSIDE!) THIS BLOCKQUOTE.</p>
</blockquote>
<p>Surprisingly, Namibia is the world’s biggest beer-drinking country, with 376 cans of beer consumed per person. As one could expect, Germany is also on top of the list. On average, German citizens drink 346 cans of beer per year. Further, there is a strong presence of Eastern-European countries, with the Czech Republic, Poland and Lithuania occupying the top positions. France and Portugal are on top when it comes to the consumption of wine, averaging 370 and 339 glasses of wine per person per year, respectively. These results come unsurprisingly and confirms the French as being wine lovers. Grenada is the world’s main spirit drinking country, closely followed by Belarus, Haiti and the Russian Federation. Again, we can confirm some cultural preferences as Russians and Belarusians are known for having appetite towards these drinks. What maybe comes with a bit of surprise is the presence of many Caribbean countries in the top positions.</p>
<p>All in all, it can be said that, with the exception of wine in France, the countries which occupy the top positions in their respective drinks’ categories, have relatively low prices for their servings. This may partially explain the above average consumption of the respective beverages.</p>
</div>
